version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"                   # AMQP порт
      - "${RABBITMQ_MANAGEMENT_PORT}:${RABBITMQ_MANAGEMENT_PORT}" # UI порт
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}

  postgres_auth:
    image: postgres:latest
    container_name: postgres_auth
    environment:
      - POSTGRES_USER=${AUTH_DATABASE_USER}
      - POSTGRES_PASSWORD=${AUTH_DATABASE_PASSWORD}
      - POSTGRES_DB=${AUTH_DATABASE_NAME}
    volumes:
      - ./postgres_data/auth:/var/lib/postgresql/data
    ports:
      - "${AUTH_DATABASE_PORT}:${AUTH_DATABASE_PORT}"

  postgres_category:
    image: postgres:latest
    container_name: postgres_category
    environment:
      - POSTGRES_USER=${CATEGORY_DATABASE_USER}
      - POSTGRES_PASSWORD=${CATEGORY_DATABASE_PASSWORD}
      - POSTGRES_DB=${CATEGORY_DATABASE_NAME}
    volumes:
      - ./postgres_data/category:/var/lib/postgresql/data
    ports:
      - "${CATEGORY_DATABASE_PORT}:${CATEGORY_DATABASE_PORT}"

  postgres_product:
    image: postgres:latest
    container_name: postgres_product
    environment:
      - POSTGRES_USER=${PRODUCT_DATABASE_USER}
      - POSTGRES_PASSWORD=${PRODUCT_DATABASE_PASSWORD}
      - POSTGRES_DB=${PRODUCT_DATABASE_NAME}
    volumes:
      - ./postgres_data/product:/var/lib/postgresql/data
    ports:
      - "${PRODUCT_DATABASE_PORT}:${PRODUCT_DATABASE_PORT}"

  auth:
    build:
      context: ./supporting/auth
    container_name: auth
    depends_on:
      - rabbitmq
      - postgres_auth
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      AUTH_DATABASE_HOST: ${AUTH_DATABASE_HOST}
      AUTH_DATABASE_PORT: ${AUTH_DATABASE_PORT}
      AUTH_DATABASE_USER: ${AUTH_DATABASE_USER}
      AUTH_DATABASE_PASSWORD: ${AUTH_DATABASE_PASSWORD}
      AUTH_DATABASE_NAME: ${AUTH_DATABASE_NAME}
      AUTH_DATABASE_URL: postgres://${AUTH_DATABASE_USER}:${AUTH_DATABASE_PASSWORD}@${AUTH_DATABASE_HOST}:${AUTH_DATABASE_PORT}/${AUTH_DATABASE_NAME}

  category:
    build:
      context: ./core/catalog
    container_name: category
    depends_on:
      - rabbitmq
      - postgres_category
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      CATEGORY_DATABASE_HOST: ${CATEGORY_DATABASE_HOST}
      CATEGORY_DATABASE_PORT: ${CATEGORY_DATABASE_PORT}
      CATEGORY_DATABASE_USER: ${CATEGORY_DATABASE_USER}
      CATEGORY_DATABASE_PASSWORD: ${CATEGORY_DATABASE_PASSWORD}
      CATEGORY_DATABASE_NAME: ${CATEGORY_DATABASE_NAME}
      CATEGORY_DATABASE_URL: postgres://${CATEGORY_DATABASE_USER}:${CATEGORY_DATABASE_PASSWORD}@${CATEGORY_DATABASE_HOST}:${CATEGORY_DATABASE_PORT}/${CATEGORY_DATABASE_NAME}

  product:
    build:
      context: ./core/product
    container_name: product
    depends_on:
      - rabbitmq
      - postgres_product
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      PRODUCT_DATABASE_HOST: ${PRODUCT_DATABASE_HOST}
      PRODUCT_DATABASE_PORT: ${PRODUCT_DATABASE_PORT}
      PRODUCT_DATABASE_USER: ${PRODUCT_DATABASE_USER}
      PRODUCT_DATABASE_PASSWORD: ${PRODUCT_DATABASE_PASSWORD}
      PRODUCT_DATABASE_NAME: ${PRODUCT_DATABASE_NAME}
      PRODUCT_DATABASE_URL: postgres://${PRODUCT_DATABASE_USER}:${PRODUCT_DATABASE_PASSWORD}@${PRODUCT_DATABASE_HOST}:${PRODUCT_DATABASE_PORT}/${PRODUCT_DATABASE_NAME}
