version: '3.9'

services:
  category_db:
    image: postgres:latest
    container_name: category_db
    environment:
      - POSTGRES_USER=${CATEGORY_DB_USER}
      - POSTGRES_PASSWORD=${CATEGORY_DB_PASS}
      - POSTGRES_DB=${CATEGORY_DB_NAME}
    volumes:
      - ./postgres_data/category:/var/lib/postgresql/data
    ports:
      - "${CATEGORY_DB_PORT}:${CATEGORY_DB_PORT}"
    command: -p ${CATEGORY_DB_PORT}

    networks:
      - backend

networks:
  backend:
    external: true

