from typing import Protocol
from uuid import UUID
from domain.entities.address import Address


class AddressRepository(Protocol):
    async def add(self, address: Address) -> None: ...
    
    async def update(self, address: Address) -> None: ...
    
    async def get_by_id(self, address_id: UUID) -> Address | None: ...
    
    async def get_by_user_id(self, user_id: UUID) -> Address | None: ...

    async def delete(self, address_id: UUID) -> None: ...
