services:
  product_db:
    image: postgres:latest
    container_name: product_db
    environment:
      - POSTGRES_USER=${PRODUCT_POSTGRES_USER}
      - POSTGRES_PASSWORD=${PRODUCT_POSTGRES_PASS}
      - POSTGRES_DB=${PRODUCT_POSTGRES_NAME}
    volumes:
      - ./postgres_data/category:/var/lib/postgresql/data
    ports:
      - "${PRODUCT_POSTGRES_PORT}:${PRODUCT_POSTGRES_PORT}"
    command: -p ${PRODUCT_POSTGRES_PORT}

    networks:
      - backend
  
  redis_cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: >
      redis-server
      --appendonly yes
      --save 900 1 
      --save 300 10 
      --save 60 10000
      --loglevel warning
      --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    
  
networks:
  backend:
    external: true

volumes:
  redis_data:
