"""fixed table relationships 

Revision ID: 9022b02f198e
Revises: 045942b7e4df
Create Date: 2025-07-11 18:45:51.266845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9022b02f198e'
down_revision: Union[str, None] = '045942b7e4df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association_product_category',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'category_id')
    )
    op.drop_constraint('brand_product_id_fkey', 'brand', type_='foreignkey')
    op.drop_column('brand', 'product_id')
    op.add_column('product', sa.Column('brand_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'product', 'brand', ['brand_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'brand_id')
    op.add_column('brand', sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('brand_product_id_fkey', 'brand', 'product', ['product_id'], ['id'])
    op.drop_table('association_product_category')
    # ### end Alembic commands ###
