"""fixed table relationships 

Revision ID: 045942b7e4df
Revises: 9b26749b6a3d
Create Date: 2025-07-11 18:23:02.945963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '045942b7e4df'
down_revision: Union[str, None] = '9b26749b6a3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_product_category')
    op.add_column('brand', sa.Column('product_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'brand', 'product', ['product_id'], ['id'])
    op.add_column('category', sa.Column('product_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'category', 'product', ['product_id'], ['id'])
    op.drop_constraint('product_brand_id_fkey', 'product', type_='foreignkey')
    op.drop_column('product', 'brand_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('brand_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('product_brand_id_fkey', 'product', 'brand', ['brand_id'], ['id'])
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_column('category', 'product_id')
    op.drop_constraint(None, 'brand', type_='foreignkey')
    op.drop_column('brand', 'product_id')
    op.create_table('association_product_category',
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='association_product_category_category_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='association_product_category_product_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'category_id', name='association_product_category_pkey')
    )
    # ### end Alembic commands ###
