"""added on delete

Revision ID: 2e5a0e0d65e9
Revises: b3aa5f1a80a3
Create Date: 2025-06-19 18:34:00.707851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e5a0e0d65e9'
down_revision: Union[str, None] = 'b3aa5f1a80a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('association_product_category_product_id_fkey', 'association_product_category', type_='foreignkey')
    op.create_foreign_key(None, 'association_product_category', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.add_column('product', sa.Column('images', postgresql.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'images')
    op.drop_constraint(None, 'association_product_category', type_='foreignkey')
    op.create_foreign_key('association_product_category_product_id_fkey', 'association_product_category', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###
