"""fixed bug for product and brand tables

Revision ID: b3aa5f1a80a3
Revises: be2f39e27c8d
Create Date: 2025-04-24 19:47:16.524474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3aa5f1a80a3'
down_revision: Union[str, None] = 'be2f39e27c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('brand_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'product', 'brand', ['brand_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'brand_id')
    # ### end Alembic commands ###
