"""Updated type

Revision ID: 38ee9841d876
Revises: bdc0a09fa093
Create Date: 2025-04-21 19:47:35.440741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38ee9841d876'
down_revision: Union[str, None] = 'bdc0a09fa093'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'attributes',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=255)),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'attributes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.ARRAY(sa.VARCHAR(length=255)),
               existing_nullable=False)
    # ### end Alembic commands ###
