"""fixed bugs and added product image table

Revision ID: e2ae27577136
Revises: 2b40e8767cf6
Create Date: 2025-06-19 19:39:48.874899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2ae27577136'
down_revision: Union[str, None] = '2b40e8767cf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_image', sa.Column('product_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'product_image', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_image', type_='foreignkey')
    op.drop_column('product_image', 'product_id')
    # ### end Alembic commands ###
