"""fixed tables

Revision ID: 51336412459c
Revises: 19070214b7b0
Create Date: 2025-07-14 19:18:46.876211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51336412459c'
down_revision: Union[str, None] = '19070214b7b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('category_product_id_fkey', 'category', type_='foreignkey')
    op.drop_column('category', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('category_product_id_fkey', 'category', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###
