"""fixed tables

Revision ID: 19070214b7b0
Revises: 9022b02f198e
Create Date: 2025-07-14 19:01:30.141733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19070214b7b0'
down_revision: Union[str, None] = '9022b02f198e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association_product_attribute',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('attribute_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'attribute_id')
    )
    op.drop_constraint('attributes_product_id_fkey', 'attributes', type_='foreignkey')
    op.drop_column('attributes', 'value')
    op.drop_column('attributes', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attributes', sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('attributes', sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('attributes_product_id_fkey', 'attributes', 'product', ['product_id'], ['id'])
    op.drop_table('association_product_attribute')
    # ### end Alembic commands ###
